### ISSUE TITLE
[Feature Request] Restrict privileged command to bot admins

### ISSUE THREAD

**Issue by Generator** [s-nagaev/hiroshi#14]
## Description
In a group or private, any user can use privileged commands (``/reset``, ``/provider``)

Restrict privileged command to bot admin(s) only.

Example: 
``ADMINS="@User1,@User2"``

**Comment by s-nagaev** [comment]
Hello! Thank you for the feature request! The proposed functionality is interesting and useful. I'm confident that I will implement it in the near future, but right now it doesn't make much sense. The fact is that even when in a group chat, Hiroshi operates an individual context when communicating with each participant of the group. That is, if a person performs a `/reset`, they erase their own communication history. There is no shared communication history kept. Not yet.

I plan to implement a special behavior for the bot in group chats in the near future, where the communication history will be shared across the entire chat. And yes, in such a case, it would be necessary to provide the feature you requested.
