### ISSUE TITLE
Some Provider got error How to resolve?

### ISSUE THREAD

**Issue by troublescope** [s-nagaev/hiroshi#17]
Here is error
`got an error: 403, message='Forbidden', url=URL('https://you.com/api/streamingSearch?userFiles=&selectedChatMode=default')`

Added proxy still no luck

**Comment by s-nagaev** [comment]
Yes, unfortunately, such a problem does exist. And the issue indeed lies with the IP: some providers, including You.com, respond with a 403 error when there's an attempt to access them from the IP addresses of major cloud providers such as AWS, Oracle, or Digital Ocean. With smaller and less well-known providers, as well as on home devices, this issue does not arise. For example, my instance is hosted with a small provider in Poland, and everything works fine there: https://t.me/hiroshi_gpt_bot
