### ISSUE TITLE
UNHEALTH PORT CHECKING

### ISSUE THREAD

**Issue by yingnengd** [s-nagaev/hiroshi#19]
Why does the port detection fail when configuring KOYEB, and the results show that it is unhealthy and cannot run. Which port do I need to EXPOSE? How to set it up?

**Comment by s-nagaev** [comment]
You don't have to expose any port, honestly :) This is a Telegram Bot that is use to using official Telegram API. The bot does not accept incoming connections and does not need to listen on any port. Accordingly, the bot does not do this :)
