### ISSUE TITLE
Error after install in docker

### ISSUE THREAD

**Issue by urtaevS** [s-nagaev/hiroshi#23]
Message in Telegram
"I'm sorry, but there seems to be a little hiccup with your request at the moment 😥 Would you mind trying again later? Don't worry, I'll be here to assist you whenever you're ready! 😼"

Log:
`PermissionError: [Errno 13] Permission denied: '/app/data/########`

**Comment by s-nagaev** [comment]
Hi! Could you show your docker-compose file or the full command you use running the app in docker?

**Comment by urtaevS** [comment]
Hi! Thank you for reply.
I've installed from docker command to Synology Container

`
docker run -d \
  -e TELEGRAM_BOT_TOKEN="token" \
  -v /volume1/docker/gpt4free_bot:/app/data \
  --name hiroshi \
  pysergio/hiroshi:latest
`

Am I missing something?
