### ISSUE TITLE
CaptchaChallenge: Use other cookies or/and ip address

### ISSUE THREAD

**Issue by urtaevS** [s-nagaev/hiroshi#28]
i got  this error
`CaptchaChallenge: Use other cookies or/and ip address`

**Comment by urtaevS** [comment]
Now i got this error
`NoneType' object has no attribute 'get'`

**Comment by s-nagaev** [comment]
I believe it's a very same issue: https://github.com/s-nagaev/hiroshi/issues/17

Some IP's are blocklisted by providers. The only thing we can do - to run the bot on the different machine.

**Comment by urtaevS** [comment]
> I believe it's a very same issue: https://github.com/s-nagaev/hiroshi/issues/17
> 
> Some IP's are blocklisted by providers. The only thing we can do - to run the bot on the different machine.
> 
> 

Like you're saying... 
Just change a provider, and bot run without errors.
