### ISSUE TITLE
got an error: [Errno 13] Permission denied: /app/data/'telegram_id'

### ISSUE THREAD

**Issue by urtaevS** [s-nagaev/hiroshi#32]
Get error in docker run command 
`docker run \
  -e TELEGRAM_BOT_TOKEN=token \
  -v /home/gptbot:/app/data \
  --name hiroshi \
  pysergio/hiroshi:latest`

**Comment by s-nagaev** [comment]
@urtaevS  Hi! You're trying to mount the whole home folder `/home/gptbot` inside the container. Are you sure this is what you're looking for? Typically, mounting the entire home directory of a user is not advisable.

I would recommend allocating a separate directory for the bot somewhere within the home directory and ensure that the user under whom the container is run has write permissions to this directory.

**Comment by urtaevS** [comment]
I think the problem is in root user in VPS, And I can configure it out how I need to bind folder. 
Now I've just start the container without mapping folders.
