### ISSUE TITLE
Installation complete. How do I proceed to run it?

### ISSUE THREAD

**Issue by klcb2010** [s-nagaev/hiroshi#34]
![截屏图片](https://github.com/s-nagaev/hiroshi/assets/32628414/f78f28e5-e98e-4dbd-ad66-92f16c1ecc92)

**Comment by s-nagaev** [comment]
@klcb2010 Since you were able to launch the bot, it means you provided a valid `TELEGRAM_BOT_TOKEN`, obtained from https://t.me/BotFather when creating the bot. Basically, you did everything necessary: now you can write to your bot in Telegram, and it will reply to you :)

**Comment by s-nagaev** [comment]
@klcb2010 aaand... it's not an installation :) You're already run it :)
